# Generated by Django 2.1 on 2020-11-18 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('content', models.TextField()),
                ('positive', models.IntegerField()),
                ('neutral', models.IntegerField()),
                ('negative', models.IntegerField()),
            ],
        ),
    ]
