# Generated by Django 2.1 on 2020-11-18 04:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='add_time',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
